# a docker compose file for mysql and adminer with a volume for the database and setup for environment variables
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sbpass-1234
      MYSQL_DATABASE: sbDataBase
      MYSQL_USER: sb
      MYSQL_PASSWORD: sbpass-1234
    ports:
      - 3306:3306 # make sure you don't have another container running on 3306
    volumes:
      - ./mysql:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
